<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Log;

class UpdateTravisIpAddresses extends Command
{
    protected $signature = "dealer:update:travis-ip";

    protected $description = "Update list of travis IP addresses";

    public function handle()
    {
        $ips = $this->getIpsFromDns();

        if (! $ips) {
            app('sentry')->captureMessage('The travis IP could not be updated.');
            return;
        }

        $content = "<?php".$this->getComment()."return ".var_export(['addresses' => $ips], true).";\n";
        file_put_contents('config/travis.php', $content);

        $this->info("Travis IP addresses updated successfully.");
    }

    private function getComment()
    {
        return "\n\n
/*
|--------------------------------------------------------------------------
| Travis configuration
|--------------------------------------------------------------------------
|
| DO NOT EDIT THIS FILE
| This file is generated automatically by the command `dealer:update:travis-ip`
|
*/
        \n\n";
    }

    private function getIpsFromDns()
    {
        $curlHandle = curl_init();

        $url = 'https://dnsjson.com/nat.travisci.net/A.json';
        curl_setopt($curlHandle, CURLOPT_URL, $url);

        $headers = [
            'Accept:application/vnd.travis-ci.2+json',
            'Content-Type:application/json',
        ];
        curl_setopt($curlHandle, CURLOPT_HTTPHEADER, $headers);

        curl_setopt($curlHandle, CURLOPT_CUSTOMREQUEST, 'GET');
        curl_setopt($curlHandle, CURLOPT_HTTPGET, true);
        curl_setopt($curlHandle, CURLOPT_POST, false);

        //Return the output instead of printing it
        curl_setopt($curlHandle, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curlHandle, CURLOPT_FAILONERROR, true);
        curl_setopt($curlHandle, CURLOPT_ENCODING, '');
        curl_setopt($curlHandle, CURLOPT_SSL_VERIFYPEER, true);
        curl_setopt($curlHandle, CURLOPT_SSL_VERIFYHOST, 2);

        $response = curl_exec($curlHandle);
        curl_close($curlHandle);

        $result = json_decode($response, true);

        if (isset($result['success']) && $result['success']) {
            return $result['results']['records'];
        }

        return false;
    }
}
